column_width = 140
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferSingle"
call_parentheses = "Always"
collapse_simple_statement = "FunctionOnly"
space_after_function_names = "Never"

[sort_requires]
enabled = true
